/// <reference types="vitest/config" />
import { execFileSync } from "node:child_process";
import { globSync } from "node:fs";
import { relative, resolve } from "node:path";
import { defineConfig, type Plugin } from "vite";

/**
 * Dev only: rebuild the posts whenever a file in writing/ is added, changed,
 * or removed, then reload the browser. A post that breaks a rule (missing
 * alt text, skipped heading, bad front matter) shows the build's message in
 * Vite's error overlay, which is a live region, so the failure is announced
 * where the writing is being read.
 */
function watchWriting(): Plugin {
  const dir = resolve(import.meta.dirname, "writing");
  return {
    name: "watch-writing",
    apply: "serve",
    configureServer(server) {
      server.watcher.add(dir);
      const rebuild = (file: string): void => {
        if (!file.startsWith(dir) || !file.endsWith(".md")) return;
        const name = relative(dir, file);
        try {
          const out = execFileSync(process.execPath, [resolve(import.meta.dirname, "scripts/build-posts.ts")], { encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] });
          server.config.logger.info(`[writing] ${name}: ${out.trim()}`, { timestamp: true });
          server.ws.send({ type: "full-reload" });
        } catch (err) {
          const message = (err as { stderr?: string }).stderr?.trim() || String(err);
          server.config.logger.error(`[writing] ${name}: ${message}`, { timestamp: true });
          server.ws.send({ type: "error", err: { message: `Post not published. ${message}`, stack: "", id: file } });
        }
      };
      server.watcher.on("add", rebuild);
      server.watcher.on("change", rebuild);
      server.watcher.on("unlink", rebuild);
    },
  };
}

// Post pages are generated by `npm run posts` into posts/<slug>/index.html.
const postPages = Object.fromEntries(
  globSync("posts/**/index.html", { cwd: import.meta.dirname }).map((p) => [
    p.replace(/[\\/]index\.html$/, "").replace(/[\\/]/g, "-"),
    resolve(import.meta.dirname, p),
  ]),
);

// User site (meredithb104.github.io) deploys at the domain root, so base stays "/".
export default defineConfig({
  plugins: [watchWriting()],
  build: {
    target: "es2023",
    modulePreload: { polyfill: false },
    rollupOptions: {
      input: {
        main: resolve(import.meta.dirname, "index.html"),
        accessibility: resolve(import.meta.dirname, "accessibility.html"),
        ...postPages,
      },
    },
  },
  test: {
    environment: "jsdom",
    include: ["src/**/*.test.ts"],
    setupFiles: ["./src/test/setup.ts"],
    css: false,
  },
});
