/// <reference types="vitest/config" />
import { globSync } from "node:fs";
import { resolve } from "node:path";
import { defineConfig } from "vite";

// Post pages are generated by `npm run posts` into posts/<slug>/index.html.
const postPages = Object.fromEntries(
  globSync("posts/**/index.html", { cwd: import.meta.dirname }).map((p) => [
    p.replace(/[\\/]index\.html$/, "").replace(/[\\/]/g, "-"),
    resolve(import.meta.dirname, p),
  ]),
);

// User site (meredithb104.github.io) deploys at the domain root, so base stays "/".
export default defineConfig({
  build: {
    target: "es2023",
    modulePreload: { polyfill: false },
    rollupOptions: {
      input: {
        main: resolve(import.meta.dirname, "index.html"),
        accessibility: resolve(import.meta.dirname, "accessibility.html"),
        ...postPages,
      },
    },
  },
  test: {
    environment: "jsdom",
    include: ["src/**/*.test.ts"],
    setupFiles: ["./src/test/setup.ts"],
    css: false,
  },
});
